baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Raechel Browne"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[menu]

[[menu.main]]
name = "The Rope That Binds Us"
url = "/#book"

[[menu.main]]
name = "About"
url = "/#about"

[[menu.main]]
name = "Blog"
url = "/post"

[[menu.main]]
name = "Contact"
url = "/#contact"

[params]
images = ["img/51ltcfcyqql._sl1360_.jpg"]

[[params.social]]
platform = "instagram"
link = "https://instagram.com/authorraechelbrowne"

[[params.social]]
platform = "facebook"
link = "https://www.facebook.com/profile.php?id=61570502693211#"

[[params.social]]
platform = "goodreads"
link = "https://www.goodreads.com/author/show/53042633.Raechel_Browne"
